in_mathzone = function()
    return vim.fn['vimtex#syntax#in_mathzone']() == 1
end

return {
    -- Mathematical symbols
    s({ wordTrig = false, trig = "/o", snippetType = "autosnippet" }, { t("\\varnothing") }, { condition = in_mathzone }),
    s({ wordTrig = false, trig = "ooo", snippetType = "autosnippet" }, { t("\\infty") }, { condition = in_mathzone }),
    s({ wordTrig = false, trig = "sum", snippetType = "autosnippet" }, { t("\\sum") }, { condition = in_mathzone }),
    s({ wordTrig = false, trig = "prod", snippetType = "autosnippet" }, { t("\\prod") }, { condition = in_mathzone }),
    s({ wordTrig = false, trig = "pm", snippetType = "autosnippet" }, { t("\\pm") }, { condition = in_mathzone }),
    s({ wordTrig = false, trig = "mp", snippetType = "autosnippet" }, { t("\\mp") }, { condition = in_mathzone }),
    s({ wordTrig = false, trig = "...", snippetType = "autosnippet" }, { t("\\dots") }, { condition = in_mathzone }),
    s({ wordTrig = false, trig = "<->", snippetType = "autosnippet" }, { t("\\leftrightarrow ") },
        { condition = in_mathzone }),
    s({ wordTrig = false, trig = "->", snippetType = "autosnippet" }, { t("\\to") }, { condition = in_mathzone }),
    s({ wordTrig = false, trig = "!>", snippetType = "autosnippet" }, { t("\\mapsto") }, { condition = in_mathzone }),
    s({ wordTrig = false, trig = "invs", snippetType = "autosnippet" }, { t("^{-1}") }, { condition = in_mathzone }),
    s({ wordTrig = false, trig = "\\\\\\", snippetType = "autosnippet" }, { t("\\setminus") },
        { condition = in_mathzone }),
    s({ wordTrig = false, trig = "||", snippetType = "autosnippet" }, { t("\\mid") }, { condition = in_mathzone }),
    s({ wordTrig = false, trig = "and", snippetType = "autosnippet" }, { t("\\cap") }, { condition = in_mathzone }),
    s({ wordTrig = false, trig = "And", snippetType = "autosnippet" }, { t("\\bigcap") }, { condition = in_mathzone }),
    s({ wordTrig = false, trig = "orr", snippetType = "autosnippet" }, { t("\\cup") }, { condition = in_mathzone }),
    s({ wordTrig = false, trig = "Orr", snippetType = "autosnippet" }, { t("\\bigcup") }, { condition = in_mathzone }),
    s({ wordTrig = false, trig = "inn", snippetType = "autosnippet" }, { t("\\in") }, { condition = in_mathzone }),
    s({ wordTrig = false, trig = "\\subset eq", snippetType = "autosnippet" }, { t("\\subseteq") },
        { condition = in_mathzone }),
    s({ wordTrig = false, trig = "=>", snippetType = "autosnippet" }, { t("\\implies") }, { condition = in_mathzone }),
    s({ wordTrig = false, trig = "=<", snippetType = "autosnippet" }, { t("\\impliedby") }, { condition = in_mathzone }),
    s({ wordTrig = false, trig = "iff", snippetType = "autosnippet" }, { t("\\iff") }, { condition = in_mathzone }),
    s({ wordTrig = false, trig = "e\\xi sts", snippetType = "autosnippet" }, { t("\\exists") },
        { condition = in_mathzone }),
    s({ wordTrig = false, trig = "===", snippetType = "autosnippet" }, { t("\\equiv") }, { condition = in_mathzone }),
    s({ wordTrig = false, trig = "Sq", snippetType = "autosnippet" }, { t("\\square") }, { condition = in_mathzone }),
    s({ wordTrig = false, trig = "!=", snippetType = "autosnippet" }, { t("\\neq") }, { condition = in_mathzone }),
    s({ wordTrig = false, trig = ">=", snippetType = "autosnippet" }, { t("\\geq") }, { condition = in_mathzone }),
    s({ wordTrig = false, trig = "<=", snippetType = "autosnippet" }, { t("\\leq") }, { condition = in_mathzone }),
    s({ wordTrig = false, trig = ">>", snippetType = "autosnippet" }, { t("\\gg") }, { condition = in_mathzone }),
    s({ wordTrig = false, trig = "<<", snippetType = "autosnippet" }, { t("\\ll") }, { condition = in_mathzone }),
    s({ wordTrig = false, trig = "~~", snippetType = "autosnippet" }, { t("\\sim") }, { condition = in_mathzone }),
    s({ wordTrig = false, trig = "\\sim ~", snippetType = "autosnippet" }, { t("\\approx") }, { condition = in_mathzone }),
    s({ wordTrig = false, trig = "prop", snippetType = "autosnippet" }, { t("\\propto") }, { condition = in_mathzone }),
    s({ wordTrig = false, trig = "nabl", snippetType = "autosnippet" }, { t("\\nabla") }, { condition = in_mathzone }),
    s({ wordTrig = false, trig = "del", snippetType = "autosnippet" }, { t("\\nabla") }, { condition = in_mathzone }),
    s({ wordTrig = false, trig = "xx", snippetType = "autosnippet" }, { t("\\times") }, { condition = in_mathzone }),
    s({ wordTrig = false, trig = "**", snippetType = "autosnippet" }, { t("\\cdot") }, { condition = in_mathzone }),
    s({ wordTrig = false, trig = "para", snippetType = "autosnippet" }, { t("\\parallel") }, { condition = in_mathzone }),
    s({ wordTrig = false, trig = "xnn", snippetType = "autosnippet" }, { t("x_{n}") }, { condition = in_mathzone }),
    -- Common subscripts
    s({ trig = "xii", snippetType = "autosnippet" }, { t("x_{i}") }, { condition = in_mathzone }),
    s({ trig = "xjj", snippetType = "autosnippet" }, { t("x_{j}") }, { condition = in_mathzone }),
    s({ trig = "xp1", snippetType = "autosnippet" }, { t("x_{n+1}") }, { condition = in_mathzone }),
    s({ trig = "ynn", snippetType = "autosnippet" }, { t("y_{n}") }, { condition = in_mathzone }),
    s({ trig = "yii", snippetType = "autosnippet" }, { t("y_{i}") }, { condition = in_mathzone }),
    s({ trig = "yjj", snippetType = "autosnippet" }, { t("y_{j}") }, { condition = in_mathzone }),
    -- Special characters
    s({ trig = "ell", snippetType = "autosnippet" }, { t("\\ell") }, { condition = in_mathzone }),
    s({ trig = "lll", snippetType = "autosnippet" }, { t("\\ell") }, { condition = in_mathzone }),
    s({ trig = "LL", snippetType = "autosnippet" }, { t("\\mathcal{L}") }, { condition = in_mathzone }),
    s({ trig = "HH", snippetType = "autosnippet" }, { t("\\mathcal{H}") }, { condition = in_mathzone }),
    s({ trig = "CC", snippetType = "autosnippet" }, { t("\\mathbb{C}") }, { condition = in_mathzone }),
    s({ trig = "RR", snippetType = "autosnippet" }, { t("\\mathbb{R}") }, { condition = in_mathzone }),
    s({ trig = "ZZ", snippetType = "autosnippet" }, { t("\\mathbb{Z}") }, { condition = in_mathzone }),
    s({ trig = "NN", snippetType = "autosnippet" }, { t("\\mathbb{N}") }, { condition = in_mathzone }),
    s({ trig = "II", snippetType = "autosnippet" }, { t("\\mathbb{1}") }, { condition = in_mathzone }),
    s({ trig = "\\mathbb{1}I", snippetType = "autosnippet" }, { t("\\hat{\\mathbb{1}}") }, { condition = in_mathzone }),
    s({ trig = "AA", snippetType = "autosnippet" }, { t("\\mathcal{A}") }, { condition = in_mathzone }),
    s({ trig = "BB", snippetType = "autosnippet" }, { t("\\mathbf{B}") }, { condition = in_mathzone }),
    s({ trig = "EE", snippetType = "autosnippet" }, { t("\\mathbf{E}") }, { condition = in_mathzone }),
    -- Unit vectors
    s({ trig = ":i", snippetType = "autosnippet" }, { t("\\mathbf{i}") }, { condition = in_mathzone }),
    s({ trig = ":j", snippetType = "autosnippet" }, { t("\\mathbf{j}") }, { condition = in_mathzone }),
    s({ trig = ":k", snippetType = "autosnippet" }, { t("\\mathbf{k}") }, { condition = in_mathzone }),
    s({ trig = ":x", snippetType = "autosnippet" }, { t("\\hat{\\mathbf{x}}") }, { condition = in_mathzone }),
    s({ trig = ":y", snippetType = "autosnippet" }, { t("\\hat{\\mathbf{y}}") }, { condition = in_mathzone }),
    s({ trig = ":z", snippetType = "autosnippet" }, { t("\\hat{\\mathbf{z}}") }, { condition = in_mathzone }),
}
